[programs.localnet]
verify_token = "5GturJxUBb95wWCwpkWCfo9ADndajYXbjMhxFhaYV584"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/maarunipandithurai/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test2 = "anchor build && anchor deploy && anchor test"